PROJECT=project 
TEX=pdflatex --shell-escape --interaction=nonstopmode -halt-on-error

all:
	$(TEX) $(PROJECT).tex

clean:
	$(RM) -rf *.log *.aux *.out *.bak *.idx *.toc *.nav *.snm *.vrb _minted-slides
% TODO: \usepackage{graphicx} required
\begin{figure}
\centering
\includegraphics[width=0.7\linewidth]{project}
\caption{}
\label{fig:project}
\end{figure}

